//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime date { get; set; }
        public decimal Subtotal { get; set; }
        public decimal tax { get; set; }
        public decimal total { get; set; }
        public int CustomerID { get; set; }
        public int OrderProductID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
